//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoBank.Cryptobankservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://localhost:46131/CryptoBankWebService")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountnumberField;
        
        private decimal balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string accountnumber {
            get {
                return this.accountnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.accountnumberField, value) != true)) {
                    this.accountnumberField = value;
                    this.RaisePropertyChanged("accountnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://localhost:46131/CryptoBankWebService", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionModel", Namespace="http://localhost:46131/CryptoBankWebService")]
    [System.SerializableAttribute()]
    public partial class TransactionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int transactionnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactiontypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverField;
        
        private double amountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int transactionnumber {
            get {
                return this.transactionnumberField;
            }
            set {
                if ((this.transactionnumberField.Equals(value) != true)) {
                    this.transactionnumberField = value;
                    this.RaisePropertyChanged("transactionnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transactiontype {
            get {
                return this.transactiontypeField;
            }
            set {
                if ((object.ReferenceEquals(this.transactiontypeField, value) != true)) {
                    this.transactiontypeField = value;
                    this.RaisePropertyChanged("transactiontype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                if ((object.ReferenceEquals(this.senderField, value) != true)) {
                    this.senderField = value;
                    this.RaisePropertyChanged("sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverField, value) != true)) {
                    this.receiverField = value;
                    this.RaisePropertyChanged("receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService", ConfigurationName="Cryptobankservice.CryptoBankServiceSoap")]
    public interface CryptoBankServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/ValidateLogin", ReplyAction="*")]
        CryptoBank.Cryptobankservice.ValidateLoginResponse ValidateLogin(CryptoBank.Cryptobankservice.ValidateLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/ValidateLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.ValidateLoginResponse> ValidateLoginAsync(CryptoBank.Cryptobankservice.ValidateLoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/GetUserByLogin", ReplyAction="*")]
        CryptoBank.Cryptobankservice.GetUserByLoginResponse GetUserByLogin(CryptoBank.Cryptobankservice.GetUserByLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/GetUserByLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.GetUserByLoginResponse> GetUserByLoginAsync(CryptoBank.Cryptobankservice.GetUserByLoginRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/RegisterUser", ReplyAction="*")]
        CryptoBank.Cryptobankservice.RegisterUserResponse RegisterUser(CryptoBank.Cryptobankservice.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.RegisterUserResponse> RegisterUserAsync(CryptoBank.Cryptobankservice.RegisterUserRequest request);
        
        // CODEGEN: Generating message contract since element name receiverAccountNumber from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransferMoney", ReplyAction="*")]
        CryptoBank.Cryptobankservice.TransferMoneyResponse TransferMoney(CryptoBank.Cryptobankservice.TransferMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransferMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransferMoneyResponse> TransferMoneyAsync(CryptoBank.Cryptobankservice.TransferMoneyRequest request);
        
        // CODEGEN: Generating message contract since element name AllUsersResult from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/AllUsers", ReplyAction="*")]
        CryptoBank.Cryptobankservice.AllUsersResponse AllUsers(CryptoBank.Cryptobankservice.AllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/AllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.AllUsersResponse> AllUsersAsync(CryptoBank.Cryptobankservice.AllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name accountNumber from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/AllTransactions", ReplyAction="*")]
        CryptoBank.Cryptobankservice.AllTransactionsResponse AllTransactions(CryptoBank.Cryptobankservice.AllTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/AllTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.AllTransactionsResponse> AllTransactionsAsync(CryptoBank.Cryptobankservice.AllTransactionsRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransactionsPerType", ReplyAction="*")]
        CryptoBank.Cryptobankservice.TransactionsPerTypeResponse TransactionsPerType(CryptoBank.Cryptobankservice.TransactionsPerTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransactionsPerType", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerTypeResponse> TransactionsPerTypeAsync(CryptoBank.Cryptobankservice.TransactionsPerTypeRequest request);
        
        // CODEGEN: Generating message contract since element name sender from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransactionsPerSender", ReplyAction="*")]
        CryptoBank.Cryptobankservice.TransactionsPerSenderResponse TransactionsPerSender(CryptoBank.Cryptobankservice.TransactionsPerSenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransactionsPerSender", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerSenderResponse> TransactionsPerSenderAsync(CryptoBank.Cryptobankservice.TransactionsPerSenderRequest request);
        
        // CODEGEN: Generating message contract since element name receiver from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransactionsPerReceiver", ReplyAction="*")]
        CryptoBank.Cryptobankservice.TransactionsPerReceiverResponse TransactionsPerReceiver(CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/TransactionsPerReceiver", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerReceiverResponse> TransactionsPerReceiverAsync(CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest request);
        
        // CODEGEN: Generating message contract since element name accountNumber from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/Finduser", ReplyAction="*")]
        CryptoBank.Cryptobankservice.FinduserResponse Finduser(CryptoBank.Cryptobankservice.FinduserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/Finduser", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.FinduserResponse> FinduserAsync(CryptoBank.Cryptobankservice.FinduserRequest request);
        
        // CODEGEN: Generating message contract since element name userAccountnumber from namespace http://localhost:46131/CryptoBankWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/DeleteUser", ReplyAction="*")]
        CryptoBank.Cryptobankservice.DeleteUserResponse DeleteUser(CryptoBank.Cryptobankservice.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:46131/CryptoBankWebService/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.DeleteUserResponse> DeleteUserAsync(CryptoBank.Cryptobankservice.DeleteUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLogin", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.ValidateLoginRequestBody Body;
        
        public ValidateLoginRequest() {
        }
        
        public ValidateLoginRequest(CryptoBank.Cryptobankservice.ValidateLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class ValidateLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateLoginRequestBody() {
        }
        
        public ValidateLoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLoginResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.ValidateLoginResponseBody Body;
        
        public ValidateLoginResponse() {
        }
        
        public ValidateLoginResponse(CryptoBank.Cryptobankservice.ValidateLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class ValidateLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateLoginResult;
        
        public ValidateLoginResponseBody() {
        }
        
        public ValidateLoginResponseBody(bool ValidateLoginResult) {
            this.ValidateLoginResult = ValidateLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByLogin", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.GetUserByLoginRequestBody Body;
        
        public GetUserByLoginRequest() {
        }
        
        public GetUserByLoginRequest(CryptoBank.Cryptobankservice.GetUserByLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class GetUserByLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetUserByLoginRequestBody() {
        }
        
        public GetUserByLoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByLoginResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.GetUserByLoginResponseBody Body;
        
        public GetUserByLoginResponse() {
        }
        
        public GetUserByLoginResponse(CryptoBank.Cryptobankservice.GetUserByLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class GetUserByLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.UserModel GetUserByLoginResult;
        
        public GetUserByLoginResponseBody() {
        }
        
        public GetUserByLoginResponseBody(CryptoBank.Cryptobankservice.UserModel GetUserByLoginResult) {
            this.GetUserByLoginResult = GetUserByLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(CryptoBank.Cryptobankservice.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.UserModel user;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(CryptoBank.Cryptobankservice.UserModel user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(CryptoBank.Cryptobankservice.RegisterUserResponseBody Body) {
            this.Body = Body;
    }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterUserResponseBody {
        
        public RegisterUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferMoney", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransferMoneyRequestBody Body;
        
        public TransferMoneyRequest() {
        }
        
        public TransferMoneyRequest(CryptoBank.Cryptobankservice.TransferMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransferMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int amountOfBitCoins;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiverAccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderAccountNumber;
        
        public TransferMoneyRequestBody() {
        }
        
        public TransferMoneyRequestBody(int amountOfBitCoins, string receiverAccountNumber, string senderAccountNumber) {
            this.amountOfBitCoins = amountOfBitCoins;
            this.receiverAccountNumber = receiverAccountNumber;
            this.senderAccountNumber = senderAccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferMoneyResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransferMoneyResponseBody Body;
        
        public TransferMoneyResponse() {
        }
        
        public TransferMoneyResponse(CryptoBank.Cryptobankservice.TransferMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransferMoneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TransferMoneyResult;
        
        public TransferMoneyResponseBody() {
        }
        
        public TransferMoneyResponseBody(bool TransferMoneyResult) {
            this.TransferMoneyResult = TransferMoneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUsers", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.AllUsersRequestBody Body;
        
        public AllUsersRequest() {
        }
        
        public AllUsersRequest(CryptoBank.Cryptobankservice.AllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllUsersRequestBody {
        
        public AllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUsersResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.AllUsersResponseBody Body;
        
        public AllUsersResponse() {
        }
        
        public AllUsersResponse(CryptoBank.Cryptobankservice.AllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class AllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.ArrayOfString AllUsersResult;
        
        public AllUsersResponseBody() {
        }
        
        public AllUsersResponseBody(CryptoBank.Cryptobankservice.ArrayOfString AllUsersResult) {
            this.AllUsersResult = AllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTransactions", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.AllTransactionsRequestBody Body;
        
        public AllTransactionsRequest() {
        }
        
        public AllTransactionsRequest(CryptoBank.Cryptobankservice.AllTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class AllTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountNumber;
        
        public AllTransactionsRequestBody() {
        }
        
        public AllTransactionsRequestBody(string accountNumber) {
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTransactionsResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.AllTransactionsResponseBody Body;
        
        public AllTransactionsResponse() {
        }
        
        public AllTransactionsResponse(CryptoBank.Cryptobankservice.AllTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class AllTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.TransactionModel[] AllTransactionsResult;
        
        public AllTransactionsResponseBody() {
        }
        
        public AllTransactionsResponseBody(CryptoBank.Cryptobankservice.TransactionModel[] AllTransactionsResult) {
            this.AllTransactionsResult = AllTransactionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsPerTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionsPerType", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransactionsPerTypeRequestBody Body;
        
        public TransactionsPerTypeRequest() {
        }
        
        public TransactionsPerTypeRequest(CryptoBank.Cryptobankservice.TransactionsPerTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransactionsPerTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountNumber;
        
        public TransactionsPerTypeRequestBody() {
        }
        
        public TransactionsPerTypeRequestBody(string type, string accountNumber) {
            this.type = type;
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsPerTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionsPerTypeResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransactionsPerTypeResponseBody Body;
        
        public TransactionsPerTypeResponse() {
        }
        
        public TransactionsPerTypeResponse(CryptoBank.Cryptobankservice.TransactionsPerTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransactionsPerTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerTypeResult;
        
        public TransactionsPerTypeResponseBody() {
        }
        
        public TransactionsPerTypeResponseBody(CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerTypeResult) {
            this.TransactionsPerTypeResult = TransactionsPerTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsPerSenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionsPerSender", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransactionsPerSenderRequestBody Body;
        
        public TransactionsPerSenderRequest() {
        }
        
        public TransactionsPerSenderRequest(CryptoBank.Cryptobankservice.TransactionsPerSenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransactionsPerSenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sender;
        
        public TransactionsPerSenderRequestBody() {
        }
        
        public TransactionsPerSenderRequestBody(string sender) {
            this.sender = sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsPerSenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionsPerSenderResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransactionsPerSenderResponseBody Body;
        
        public TransactionsPerSenderResponse() {
        }
        
        public TransactionsPerSenderResponse(CryptoBank.Cryptobankservice.TransactionsPerSenderResponseBody Body) {
            this.Body = Body;
    }
    }
    
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransactionsPerSenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerSenderResult;
        
        public TransactionsPerSenderResponseBody() {
        }
        
        public TransactionsPerSenderResponseBody(CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerSenderResult) {
            this.TransactionsPerSenderResult = TransactionsPerSenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsPerReceiverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionsPerReceiver", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransactionsPerReceiverRequestBody Body;
        
        public TransactionsPerReceiverRequest() {
        }
        
        public TransactionsPerReceiverRequest(CryptoBank.Cryptobankservice.TransactionsPerReceiverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransactionsPerReceiverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receiver;
        
        public TransactionsPerReceiverRequestBody() {
        }
        
        public TransactionsPerReceiverRequestBody(string receiver) {
            this.receiver = receiver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsPerReceiverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionsPerReceiverResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.TransactionsPerReceiverResponseBody Body;
        
        public TransactionsPerReceiverResponse() {
        }
        
        public TransactionsPerReceiverResponse(CryptoBank.Cryptobankservice.TransactionsPerReceiverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class TransactionsPerReceiverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerReceiverResult;
        
        public TransactionsPerReceiverResponseBody() {
        }
        
        public TransactionsPerReceiverResponseBody(CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerReceiverResult) {
            this.TransactionsPerReceiverResult = TransactionsPerReceiverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinduserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Finduser", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.FinduserRequestBody Body;
        
        public FinduserRequest() {
        }
        
        public FinduserRequest(CryptoBank.Cryptobankservice.FinduserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class FinduserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountNumber;
        
        public FinduserRequestBody() {
        }
        
        public FinduserRequestBody(string accountNumber) {
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinduserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinduserResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.FinduserResponseBody Body;
        
        public FinduserResponse() {
        }
        
        public FinduserResponse(CryptoBank.Cryptobankservice.FinduserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class FinduserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CryptoBank.Cryptobankservice.UserModel[] FinduserResult;
        
        public FinduserResponseBody() {
        }
        
        public FinduserResponseBody(CryptoBank.Cryptobankservice.UserModel[] FinduserResult) {
            this.FinduserResult = FinduserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(CryptoBank.Cryptobankservice.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:46131/CryptoBankWebService")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userAccountnumber;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string userAccountnumber) {
            this.userAccountnumber = userAccountnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://localhost:46131/CryptoBankWebService", Order=0)]
        public CryptoBank.Cryptobankservice.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(CryptoBank.Cryptobankservice.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteUserResponseBody {
        
        public DeleteUserResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CryptoBankServiceSoapChannel : CryptoBank.Cryptobankservice.CryptoBankServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CryptoBankServiceSoapClient : System.ServiceModel.ClientBase<CryptoBank.Cryptobankservice.CryptoBankServiceSoap>, CryptoBank.Cryptobankservice.CryptoBankServiceSoap {
        
        public CryptoBankServiceSoapClient() {
        }
        
        public CryptoBankServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CryptoBankServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoBankServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoBankServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.ValidateLoginResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.ValidateLogin(CryptoBank.Cryptobankservice.ValidateLoginRequest request) {
            return base.Channel.ValidateLogin(request);
        }
        
        public bool ValidateLogin(string email, string password) {
            CryptoBank.Cryptobankservice.ValidateLoginRequest inValue = new CryptoBank.Cryptobankservice.ValidateLoginRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.ValidateLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            CryptoBank.Cryptobankservice.ValidateLoginResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).ValidateLogin(inValue);
            return retVal.Body.ValidateLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.ValidateLoginResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.ValidateLoginAsync(CryptoBank.Cryptobankservice.ValidateLoginRequest request) {
            return base.Channel.ValidateLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.ValidateLoginResponse> ValidateLoginAsync(string email, string password) {
            CryptoBank.Cryptobankservice.ValidateLoginRequest inValue = new CryptoBank.Cryptobankservice.ValidateLoginRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.ValidateLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).ValidateLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.GetUserByLoginResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.GetUserByLogin(CryptoBank.Cryptobankservice.GetUserByLoginRequest request) {
            return base.Channel.GetUserByLogin(request);
        }
        
        public CryptoBank.Cryptobankservice.UserModel GetUserByLogin(string email, string password) {
            CryptoBank.Cryptobankservice.GetUserByLoginRequest inValue = new CryptoBank.Cryptobankservice.GetUserByLoginRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.GetUserByLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            CryptoBank.Cryptobankservice.GetUserByLoginResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).GetUserByLogin(inValue);
            return retVal.Body.GetUserByLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.GetUserByLoginResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.GetUserByLoginAsync(CryptoBank.Cryptobankservice.GetUserByLoginRequest request) {
            return base.Channel.GetUserByLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.GetUserByLoginResponse> GetUserByLoginAsync(string email, string password) {
            CryptoBank.Cryptobankservice.GetUserByLoginRequest inValue = new CryptoBank.Cryptobankservice.GetUserByLoginRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.GetUserByLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).GetUserByLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.RegisterUserResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.RegisterUser(CryptoBank.Cryptobankservice.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public void RegisterUser(CryptoBank.Cryptobankservice.UserModel user) {
            CryptoBank.Cryptobankservice.RegisterUserRequest inValue = new CryptoBank.Cryptobankservice.RegisterUserRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.RegisterUserRequestBody();
            inValue.Body.user = user;
            CryptoBank.Cryptobankservice.RegisterUserResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).RegisterUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.RegisterUserResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.RegisterUserAsync(CryptoBank.Cryptobankservice.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.RegisterUserResponse> RegisterUserAsync(CryptoBank.Cryptobankservice.UserModel user) {
            CryptoBank.Cryptobankservice.RegisterUserRequest inValue = new CryptoBank.Cryptobankservice.RegisterUserRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.RegisterUserRequestBody();
            inValue.Body.user = user;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).RegisterUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.TransferMoneyResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransferMoney(CryptoBank.Cryptobankservice.TransferMoneyRequest request) {
            return base.Channel.TransferMoney(request);
        }
        
        public bool TransferMoney(int amountOfBitCoins, string receiverAccountNumber, string senderAccountNumber) {
            CryptoBank.Cryptobankservice.TransferMoneyRequest inValue = new CryptoBank.Cryptobankservice.TransferMoneyRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransferMoneyRequestBody();
            inValue.Body.amountOfBitCoins = amountOfBitCoins;
            inValue.Body.receiverAccountNumber = receiverAccountNumber;
            inValue.Body.senderAccountNumber = senderAccountNumber;
            CryptoBank.Cryptobankservice.TransferMoneyResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransferMoney(inValue);
            return retVal.Body.TransferMoneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransferMoneyResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransferMoneyAsync(CryptoBank.Cryptobankservice.TransferMoneyRequest request) {
            return base.Channel.TransferMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransferMoneyResponse> TransferMoneyAsync(int amountOfBitCoins, string receiverAccountNumber, string senderAccountNumber) {
            CryptoBank.Cryptobankservice.TransferMoneyRequest inValue = new CryptoBank.Cryptobankservice.TransferMoneyRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransferMoneyRequestBody();
            inValue.Body.amountOfBitCoins = amountOfBitCoins;
            inValue.Body.receiverAccountNumber = receiverAccountNumber;
            inValue.Body.senderAccountNumber = senderAccountNumber;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransferMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.AllUsersResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.AllUsers(CryptoBank.Cryptobankservice.AllUsersRequest request) {
            return base.Channel.AllUsers(request);
        }
        
        public CryptoBank.Cryptobankservice.ArrayOfString AllUsers() {
            CryptoBank.Cryptobankservice.AllUsersRequest inValue = new CryptoBank.Cryptobankservice.AllUsersRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.AllUsersRequestBody();
            CryptoBank.Cryptobankservice.AllUsersResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).AllUsers(inValue);
            return retVal.Body.AllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.AllUsersResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.AllUsersAsync(CryptoBank.Cryptobankservice.AllUsersRequest request) {
            return base.Channel.AllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.AllUsersResponse> AllUsersAsync() {
            CryptoBank.Cryptobankservice.AllUsersRequest inValue = new CryptoBank.Cryptobankservice.AllUsersRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.AllUsersRequestBody();
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).AllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.AllTransactionsResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.AllTransactions(CryptoBank.Cryptobankservice.AllTransactionsRequest request) {
            return base.Channel.AllTransactions(request);
        }
        
        public CryptoBank.Cryptobankservice.TransactionModel[] AllTransactions(string accountNumber) {
            CryptoBank.Cryptobankservice.AllTransactionsRequest inValue = new CryptoBank.Cryptobankservice.AllTransactionsRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.AllTransactionsRequestBody();
            inValue.Body.accountNumber = accountNumber;
            CryptoBank.Cryptobankservice.AllTransactionsResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).AllTransactions(inValue);
            return retVal.Body.AllTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.AllTransactionsResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.AllTransactionsAsync(CryptoBank.Cryptobankservice.AllTransactionsRequest request) {
            return base.Channel.AllTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.AllTransactionsResponse> AllTransactionsAsync(string accountNumber) {
            CryptoBank.Cryptobankservice.AllTransactionsRequest inValue = new CryptoBank.Cryptobankservice.AllTransactionsRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.AllTransactionsRequestBody();
            inValue.Body.accountNumber = accountNumber;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).AllTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.TransactionsPerTypeResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransactionsPerType(CryptoBank.Cryptobankservice.TransactionsPerTypeRequest request) {
            return base.Channel.TransactionsPerType(request);
        }
        
        public CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerType(string type, string accountNumber) {
            CryptoBank.Cryptobankservice.TransactionsPerTypeRequest inValue = new CryptoBank.Cryptobankservice.TransactionsPerTypeRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransactionsPerTypeRequestBody();
            inValue.Body.type = type;
            inValue.Body.accountNumber = accountNumber;
            CryptoBank.Cryptobankservice.TransactionsPerTypeResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransactionsPerType(inValue);
            return retVal.Body.TransactionsPerTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerTypeResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransactionsPerTypeAsync(CryptoBank.Cryptobankservice.TransactionsPerTypeRequest request) {
            return base.Channel.TransactionsPerTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerTypeResponse> TransactionsPerTypeAsync(string type, string accountNumber) {
            CryptoBank.Cryptobankservice.TransactionsPerTypeRequest inValue = new CryptoBank.Cryptobankservice.TransactionsPerTypeRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransactionsPerTypeRequestBody();
            inValue.Body.type = type;
            inValue.Body.accountNumber = accountNumber;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransactionsPerTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.TransactionsPerSenderResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransactionsPerSender(CryptoBank.Cryptobankservice.TransactionsPerSenderRequest request) {
            return base.Channel.TransactionsPerSender(request);
        }
        
        public CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerSender(string sender) {
            CryptoBank.Cryptobankservice.TransactionsPerSenderRequest inValue = new CryptoBank.Cryptobankservice.TransactionsPerSenderRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransactionsPerSenderRequestBody();
            inValue.Body.sender = sender;
            CryptoBank.Cryptobankservice.TransactionsPerSenderResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransactionsPerSender(inValue);
            return retVal.Body.TransactionsPerSenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerSenderResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransactionsPerSenderAsync(CryptoBank.Cryptobankservice.TransactionsPerSenderRequest request) {
            return base.Channel.TransactionsPerSenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerSenderResponse> TransactionsPerSenderAsync(string sender) {
            CryptoBank.Cryptobankservice.TransactionsPerSenderRequest inValue = new CryptoBank.Cryptobankservice.TransactionsPerSenderRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransactionsPerSenderRequestBody();
            inValue.Body.sender = sender;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransactionsPerSenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.TransactionsPerReceiverResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransactionsPerReceiver(CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest request) {
            return base.Channel.TransactionsPerReceiver(request);
        }
        
        public CryptoBank.Cryptobankservice.TransactionModel[] TransactionsPerReceiver(string receiver) {
            CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest inValue = new CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransactionsPerReceiverRequestBody();
            inValue.Body.receiver = receiver;
            CryptoBank.Cryptobankservice.TransactionsPerReceiverResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransactionsPerReceiver(inValue);
            return retVal.Body.TransactionsPerReceiverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerReceiverResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.TransactionsPerReceiverAsync(CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest request) {
            return base.Channel.TransactionsPerReceiverAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.TransactionsPerReceiverResponse> TransactionsPerReceiverAsync(string receiver) {
            CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest inValue = new CryptoBank.Cryptobankservice.TransactionsPerReceiverRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.TransactionsPerReceiverRequestBody();
            inValue.Body.receiver = receiver;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).TransactionsPerReceiverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.FinduserResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.Finduser(CryptoBank.Cryptobankservice.FinduserRequest request) {
            return base.Channel.Finduser(request);
        }
        
        public CryptoBank.Cryptobankservice.UserModel[] Finduser(string accountNumber) {
            CryptoBank.Cryptobankservice.FinduserRequest inValue = new CryptoBank.Cryptobankservice.FinduserRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.FinduserRequestBody();
            inValue.Body.accountNumber = accountNumber;
            CryptoBank.Cryptobankservice.FinduserResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).Finduser(inValue);
            return retVal.Body.FinduserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.FinduserResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.FinduserAsync(CryptoBank.Cryptobankservice.FinduserRequest request) {
            return base.Channel.FinduserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.FinduserResponse> FinduserAsync(string accountNumber) {
            CryptoBank.Cryptobankservice.FinduserRequest inValue = new CryptoBank.Cryptobankservice.FinduserRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.FinduserRequestBody();
            inValue.Body.accountNumber = accountNumber;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).FinduserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoBank.Cryptobankservice.DeleteUserResponse CryptoBank.Cryptobankservice.CryptoBankServiceSoap.DeleteUser(CryptoBank.Cryptobankservice.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public void DeleteUser(string userAccountnumber) {
            CryptoBank.Cryptobankservice.DeleteUserRequest inValue = new CryptoBank.Cryptobankservice.DeleteUserRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.DeleteUserRequestBody();
            inValue.Body.userAccountnumber = userAccountnumber;
            CryptoBank.Cryptobankservice.DeleteUserResponse retVal = ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).DeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.DeleteUserResponse> CryptoBank.Cryptobankservice.CryptoBankServiceSoap.DeleteUserAsync(CryptoBank.Cryptobankservice.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoBank.Cryptobankservice.DeleteUserResponse> DeleteUserAsync(string userAccountnumber) {
            CryptoBank.Cryptobankservice.DeleteUserRequest inValue = new CryptoBank.Cryptobankservice.DeleteUserRequest();
            inValue.Body = new CryptoBank.Cryptobankservice.DeleteUserRequestBody();
            inValue.Body.userAccountnumber = userAccountnumber;
            return ((CryptoBank.Cryptobankservice.CryptoBankServiceSoap)(this)).DeleteUserAsync(inValue);
        }
    }
}
