//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transactionnumber { get; set; }
        public string transactiontype { get; set; }
        public System.DateTime date { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public double amount { get; set; }
    
        public virtual User User { get; set; }
    }
}
